import type { components } from './schema';

export type ApiSchemas = components['schemas'];
export type User = ApiSchemas['UserResponse'];
export type UserProfile = ApiSchemas['UserProfileResponse'];
export type UserProfileUpdate = ApiSchemas['UserProfileUpdate'];
export type Exercise = ApiSchemas['ExerciseCatalogItem'];
export type ExerciseGuide = ApiSchemas['ExerciseGuide'];
export type PublicExerciseSummary = ApiSchemas['PublicExerciseSummary'];
export type PublicExerciseDetail = ApiSchemas['PublicExerciseDetail'];
export type ProgramTemplate = ApiSchemas['ProgramTemplateResponse'];
export type ProgramTemplateCreate = ApiSchemas['ProgramTemplateCreate'];
export type ProgramRecommendationRequest = ApiSchemas['ProgramRecommendationRequest'];
export type ProgramRecommendationResponse = ApiSchemas['ProgramRecommendationResponse'];
export type Client = ApiSchemas['ClientResponse'];
export type CoachAssignedProgram = ApiSchemas['CoachAssignedProgramResponse'];
export type Workout = ApiSchemas['WorkoutTodayResponse'];
export type WorkoutStatus = ApiSchemas['WorkoutStatusResponse'];
export type WorkoutScheduleItem = ApiSchemas['WorkoutScheduleItem'];
export type WorkoutHistoryItem = ApiSchemas['WorkoutHistoryItem'];
export type WorkoutHistorySummary = ApiSchemas['WorkoutHistorySummary'];
export type WorkoutAdaptationRequest = ApiSchemas['WorkoutAdaptationRequest'];
export type WorkoutAdaptationPreview = ApiSchemas['WorkoutAdaptationPreviewResponse'];
export type WorkoutAdaptationApply = ApiSchemas['WorkoutAdaptationApplyResponse'];
export type WorkoutAlternative = ApiSchemas['WorkoutAlternativeItem'];
export type BodyMeasurement = ApiSchemas['BodyMeasurementResponse'];
export type BodyMeasurementSave = ApiSchemas['BodyMeasurementSave'];
export type CardioSession = ApiSchemas['CardioSessionResponse'];
export type CardioSessionCreate = ApiSchemas['CardioSessionCreate'];
export type CardioSessionUpdate = ApiSchemas['CardioSessionUpdate'];
export type FoodDiaryDay = ApiSchemas['FoodDiaryDayResponse'];
export type FoodDiaryEntry = ApiSchemas['FoodDiaryEntryResponse'];
export type FoodDiaryMeal = ApiSchemas['FoodDiaryMeal'];
export type FoodDiaryNutrition = ApiSchemas['FoodDiaryNutrition'];
export type Food = ApiSchemas['FoodResponse'];
export type FoodList = ApiSchemas['FoodListResponse'];
export type FoodSearch = ApiSchemas['FoodSearchResponse'];
export type FoodBarcodeLookup = ApiSchemas['FoodBarcodeLookupResponse'];
export type ExternalFood = ApiSchemas['ExternalFoodResponse'];
export type UserFoodCreate = ApiSchemas['UserFoodCreate'];
export type UserFoodUpdate = ApiSchemas['UserFoodUpdate'];
export type Recipe = ApiSchemas['RecipeResponse'];
export type RecipeList = ApiSchemas['RecipeListResponse'];
export type RecipeCreate = ApiSchemas['RecipeCreate'];
export type FoodDiaryCopyResponse = ApiSchemas['FoodDiaryCopyResponse'];
export type NutritionTarget = ApiSchemas['NutritionTargetResponse'];
export type NutritionTargetHistory = ApiSchemas['NutritionTargetHistoryResponse'];
export type NutritionTargetSave = ApiSchemas['NutritionTargetSave'];
export type EnergyCalibration = ApiSchemas['EnergyCalibrationResponse'];
export type EnergyCalibrationHistory = ApiSchemas['EnergyCalibrationHistoryResponse'];
export type NotificationItem = ApiSchemas['NotificationResponse'];
export type NotificationSetting = ApiSchemas['NotificationSettingResponse'];
export type WeeklyCheckInCurrent = ApiSchemas['WeeklyCheckInCurrentResponse'];
export type WeeklyCheckInHistory = ApiSchemas['WeeklyCheckInHistoryResponse'];
export type WeeklyCheckInSubmit = ApiSchemas['WeeklyCheckInSubmitRequest'];
export type AdminUser = ApiSchemas['AdminUserRow'];
export type AdminNotification = ApiSchemas['AdminNotificationRow'];
export type AdminTemplate = ApiSchemas['AdminTemplateRow'];
export type AdminCoachRoleApplication = ApiSchemas['AdminCoachRoleApplicationRow'];
export type CoachRoleApplication = ApiSchemas['CoachRoleApplicationResponse'];
export type InviteLink = ApiSchemas['CoachInviteLinkResponse'];
export type CoachInvitePreview = ApiSchemas['CoachInvitePreviewResponse'];
export type TelegramLinkCreate = ApiSchemas['TelegramLinkCreateResponse'];
export type OAuthLinkCreate = ApiSchemas['OAuthLinkCreateResponse'];
export type AccountExportStatus = ApiSchemas['AccountExportStatusResponse'];
export type AccountExportDownloadLink = ApiSchemas['AccountExportDownloadLinkResponse'];
export type ProgressVolumePoint = ApiSchemas['ProgressVolumePoint'];
export type WorkoutProgress = ApiSchemas['WorkoutProgressResponse'];
export type WorkoutTimelineItem = ApiSchemas['WorkoutTimelineItem'];
export type WorkoutComment = ApiSchemas['WorkoutCommentResponse'];
export type ProgressSummary = ApiSchemas['ProgressSummaryResponse'];
export type NutritionReport = ApiSchemas['NutritionReportResponse'];
export type NutritionReportPeriod = ApiSchemas['NutritionReportPeriod'];
export type TrainingAnalytics = ApiSchemas['TrainingAnalyticsResponse'];
export type TrainerClientProgressSummary = ApiSchemas['TrainerClientProgressSummary'];
export type TrainerClientProgressList = ApiSchemas['TrainerClientProgressListResponse'];

export interface PublicConfig {
  app_env: string;
  enable_dev_auth: boolean;
  enable_web_auth: boolean;
  enable_email_auth: boolean;
  telegram_bot_username: string;
  oauth_providers: string[];
}
